### ISSUE TITLE
Unknown storage engine MyISAM (first time test run)

### ISSUE THREAD

**Issue by joonasvanhatapio** [WordPress/phpunit-test-runner#89] opened 2019-04-04 08:27 UTC
Hello,

I just got our testing server running and executed the first time tests and it appeared to have failed (https://make.wordpress.org/hosting/test-results/r45108/wpcloudbot-r45108/)

During the test.php running I get lots of errors due to specification of DB creation with "ENGINE=MyISAM".
We have MariaDB Galera Cluster in use, which only supports InnoDB (forced) as the engine and therefore gives an error message of unsupported DB engine.

```
$ php test.php
Environment variables pass checks.
cd '/tmp/wp-test-runner'; php phpunit.phar

PHP version: 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 (/usr/bin/php7.3)

Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.............................................................   61 / 9562 (  0%)
.............................................................  122 / 9562 (  1%)
.............................................................  183 / 9562 (  1%)
.............................................................  244 / 9562 (  2%)
.............................................................  305 / 9562 (  3%)
.............................................................  366 / 9562 (  3%)
.............................................................  427 / 9562 (  4%)
.............................................................  488 / 9562 (  5%)
.............................................................  549 / 9562 (  5%)
.............................................................  610 / 9562 (  6%)
.............................................................  671 / 9562 (  7%)
.............................................................  732 / 9562 (  7%)
.............................................................  793 / 9562 (  8%)
.............................................................  854 / 9562 (  8%)
.............................................................  915 / 9562 (  9%)
.............................................................  976 / 9562 ( 10%)
............................................................. 1037 / 9562 ( 10%)
............................................................. 1098 / 9562 ( 11%)
............................................................. 1159 / 9562 ( 12%)
............................................................. 1220 / 9562 ( 12%)
............................................................. 1281 / 9562 ( 13%)
............................................................. 1342 / 9562 ( 14%)
............................................................. 1403 / 9562 ( 14%)
............................................................. 1464 / 9562 ( 15%)
............................................................. 1525 / 9562 ( 15%)
............................................................. 1586 / 9562 ( 16%)
............................................................. 1647 / 9562 ( 17%)
............................................................. 1708 / 9562 ( 17%)
............................................................. 1769 / 9562 ( 18%)
............................................................. 1830 / 9562 ( 19%)
............................................................. 1891 / 9562 ( 19%)
............................................................. 1952 / 9562 ( 20%)
............................................................. 2013 / 9562 ( 21%)
............................................................. 2074 / 9562 ( 21%)
.....................S....................................... 2135 / 9562 ( 22%)
............................................................. 2196 / 9562 ( 22%)
............................................................. 2257 / 9562 ( 23%)
............................................................. 2318 / 9562 ( 24%)
............................................................. 2379 / 9562 ( 24%)
...................S.S....................................... 2440 / 9562 ( 25%)
............................................................. 2501 / 9562 ( 26%)
..........................S.................................. 2562 / 9562 ( 26%)
.......................WordPress database error Unknown storage engine 'MyISAM' for query
                        CREATE TABLE wptests__dbdelta_test (
                                id bigint(20) NOT NULL AUTO_INCREMENT,
                                column_1 varchar(255) NOT NULL,
                                column_2 text,
                                column_3 blob,
                                PRIMARY KEY  (id),
                                KEY key_1 (column_1(191)),
                                KEY compound_key (id,column_1(191)),
                                FULLTEXT KEY fulltext_key (column_1)
                        ) ENGINE=MyISAM
                         made by PHPUnit_TextUI_Command::main, PHPUnit_TextUI_Command->run, PHPUnit_TextUI_TestRunner->doRun, PHPUnit_Framework_TestSuite->run, PHPUnit_Framework_TestSuite->run, PHPUnit_Framework_TestSuite->run, PHPUnit_Framework_TestCase->run, PHPUnit_Framework_TestResult->run, PHPUnit_Framework_TestCase->runBare, Tests_dbDelta->setUp
.<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Unknown storage engine &#039;MyISAM&#039;]<br /><code>

**Lot's of those repeating**

......
You should really fix these slow tests (>150ms)...
 1. 1018ms to run WP_Test_REST_Users_Controller:test_get_items_pagination_headers
 2. 789ms to run Tests_Media:test_oembed_explicit_media_link
 3. 668ms to run Tests_Media:test_multiline_comment_with_embeds
 4. 598ms to run WP_Test_REST_Posts_Controller:test_get_items_pagination_headers
 5. 595ms to run Tests_Image_Functions:test_inferred_mime_types
 6. 493ms to run WP_Test_REST_Users_Controller:test_get_items_per_page
 7. 488ms to run Tests_WP_Customize_Manager:test_import_theme_starter_content
 8. 476ms to run WP_Test_REST_Users_Controller:test_get_items_page
 9. 461ms to run Tests_Import_Import:test_double_import
 10. 453ms to run Tests_WP_Site_Icon:test_insert_cropped_attachment
...and there are 35 more above your threshold hidden from view

Time: 2.66 minutes, Memory: 186.50MB

There was 1 error:

1) Tests_Image_Functions::test_pdf_preview_doesnt_overwrite_existing_jpeg
Undefined index: sizes

/tmp/wp-test-runner/tests/phpunit/tests/image/functions.php:620

--

There were 26 failures:

1) Tests_dbDelta::test_existing_table
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
 )

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:121

2) Tests_dbDelta::test_column_type_change
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'wptests__dbdelta_test.id' => 'Changed type of wptests__dbde...nt(11)'
+    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
 )

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:147

3) Tests_dbDelta::test_column_added
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'wptests__dbdelta_test.extra_col' => 'Added column wptests__dbdelta...ra_col'
+    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
 )

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:176

4) Tests_dbDelta::test_columns_arent_removed
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
 )

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:206

5) Tests_dbDelta::test_no_execution
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'wptests__dbdelta_test.extra_col' => 'Added column wptests__dbdelta...ra_col'
+    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
 )

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:236

6) Tests_dbDelta::test_insert_into_table
null does not match expected type "object".

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:308
/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:259

7) Tests_dbDelta::test_fulltext_index
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:285

8) Tests_dbDelta::test_dont_downsize_text_fields
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 ().

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:425

9) Tests_dbDelta::test_dont_downsize_blob_fields
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 ().

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:450

10) Tests_dbDelta::test_upsize_text_fields
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 (
    'wptests__dbdelta_test.column_2' => 'Changed type of wptests__dbdelta_test.column_2 from text to bigtext'
).

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:478

11) Tests_dbDelta::test_upsize_blob_fields
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 (
    'wptests__dbdelta_test.column_3' => 'Changed type of wptests__dbdelta_test.column_3 from blob to mediumblob'
).

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:509

12) Tests_dbDelta::test_spatial_indices
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:563

13) Tests_dbDelta::test_index_with_a_reserved_keyword_can_be_created
Failed asserting that actual size 0 matches expected size 2.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:643

14) Tests_dbDelta::test_key_and_index_and_fulltext_key_and_fulltext_index_and_unique_key_and_unique_index_indicies
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 (
    0 => 'Added index wptests__dbdelta_test KEY `key_2` (`column_1`(191))'
    1 => 'Added index wptests__dbdelta_test UNIQUE KEY `key_3` (`column_1`(191))'
    2 => 'Added index wptests__dbdelta_test UNIQUE KEY `key_4` (`column_1`(191))'
    3 => 'Added index wptests__dbdelta_test FULLTEXT KEY `key_5` (`column_1`)'
).

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:689

15) Tests_dbDelta::test_index_and_key_are_synonyms_and_do_not_recreate_indices
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:722

16) Tests_dbDelta::test_indices_with_prefix_limits_are_created_and_do_not_recreate_indices
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 (
    0 => 'Added index wptests__dbdelta_test KEY `key_2` (`column_1`(10))'
    1 => 'Added index wptests__dbdelta_test KEY `key_3` (`column_2`(100),`column_1`(10))'
).

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:749

17) Tests_dbDelta::test_index_col_names_with_order_do_not_recreate_indices
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:780

18) Tests_dbDelta::test_primary_key_with_single_space_does_not_recreate_index
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:804

19) Tests_dbDelta::test_index_definitions_with_spaces_do_not_recreate_indices
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:828

20) Tests_dbDelta::test_index_types_are_not_case_sensitive_and_do_not_recreate_indices
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:852

21) Tests_dbDelta::test_key_names_are_not_case_sensitive_and_do_not_recreate_indices
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:877

22) Tests_dbDelta::test_unchanged_key_lengths_do_not_recreate_index
Failed asserting that an array is empty.

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:902

23) Tests_dbDelta::test_changed_key_lengths_do_not_recreate_index
Failed asserting that Array &0 (
    'wptests__dbdelta_test' => 'Created table wptests__dbdelta_test'
) is identical to Array &0 (
    0 => 'Added index wptests__dbdelta_test KEY `changing_key_length` (`column_1`(20))'
).

/tmp/wp-test-runner/tests/phpunit/tests/dbdelta.php:929

24) Tests_Image_Functions::test_wp_generate_attachment_metadata_pdf
Failed asserting that Array &0 () is identical to Array &0 (
    'sizes' => Array &1 (
        'thumbnail' => Array &2 (
            'file' => 'wordpress-gsoc-flyer-pdf-116x150.jpg'
            'width' => 116
            'height' => 150
            'mime-type' => 'image/jpeg'
        )
        'medium' => Array &3 (
            'file' => 'wordpress-gsoc-flyer-pdf-232x300.jpg'
            'width' => 232
            'height' => 300
            'mime-type' => 'image/jpeg'
        )
        'large' => Array &4 (
            'file' => 'wordpress-gsoc-flyer-pdf-791x1024.jpg'
            'width' => 791
            'height' => 1024
            'mime-type' => 'image/jpeg'
        )
        'full' => Array &5 (
            'file' => 'wordpress-gsoc-flyer-pdf.jpg'
            'width' => 1088
            'height' => 1408
            'mime-type' => 'image/jpeg'
        )
    )
).

/tmp/wp-test-runner/tests/phpunit/tests/image/functions.php:466

25) Tests_Image_Functions::test_crop_setting_for_pdf
Failed asserting that Array &0 () is identical to Array &0 (
    'sizes' => Array &1 (
        'thumbnail' => Array &2 (
            'file' => 'wordpress-gsoc-flyer-pdf-116x150.jpg'
            'width' => 116
            'height' => 150
            'mime-type' => 'image/jpeg'
        )
        'medium' => Array &3 (
            'file' => 'wordpress-gsoc-flyer-pdf-300x300.jpg'
            'width' => 300
            'height' => 300
            'mime-type' => 'image/jpeg'
        )
        'large' => Array &4 (
            'file' => 'wordpress-gsoc-flyer-pdf-791x1024.jpg'
            'width' => 791
            'height' => 1024
            'mime-type' => 'image/jpeg'
        )
        'full' => Array &5 (
            'file' => 'wordpress-gsoc-flyer-pdf.jpg'
            'width' => 1088
            'height' => 1408
            'mime-type' => 'image/jpeg'
        )
    )
).

/tmp/wp-test-runner/tests/phpunit/tests/image/functions.php:531

26) Tests_Image_Functions::test_fallback_intermediate_image_sizes
The `test-size` was not added to the metadata.
Failed asserting that false is true.

/tmp/wp-test-runner/tests/phpunit/tests/image/functions.php:572

ERRORS!
Tests: 9562, Assertions: 73759, Errors: 1, Failures: 26, Skipped: 14.
Error: Failed to perform operation.

```

**Comment by mrxkon** [comment] 2020-02-05 10:18
Hey @joonasvanhatapio and thanks so much for the report!

The team [chatted about this](https://wordpress.slack.com/archives/C3D6T7F8Q/p1580895915099800) in the weekly hosting meeting today.

It looks like the problem is in the [tests themselves](https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/dbdelta.php#L49), rather than in the test runner, unfortunately.

Consensus in the meeting was that WordPress should better support InnoDB in these tests and a [ticket](https://core.trac.wordpress.org/ticket/49367) in WordPress' core trac for further discussion was created.

Thanks again and sorry for the long wait on a reply!

**Comment by mrxkon** [comment] 2020-02-05 18:31
Hey @joonasvanhatapio ! 

Following up here, a patch has just been committed for this so it would be nice to get some feedback if everything is running now as expected.

You can also see the commit here https://core.trac.wordpress.org/changeset/47193 .

If all is good we can close this issue as well 😄 !

**Closed** 2024-02-07 09:15 UTC
Labels: bug, reporter-feedback
